### ISSUE TITLE
Incorrect cast to avro schema for 1:1* connections

### ISSUE THREAD

**Issue by opomuc** [tarantool/graphql.0#165]
```
query linked_data($uid: String) {
  relations(uid: $uid) {
    uid
    individual {
      last_name
    }
    organization {
      business_name
    }
  }
}
```
If we call `query:avro_schema()` on compiled query above we get:
```
type: record
name: Query
fields:
- name: relations
  type:
    type: array
    items:
      type: record
      fields:
      - name: uid
        type: string
      - name: individual
        type: record*
      - name: organization
        type: record*
      name: relations
      namespace: Query
...
```
`individual` and `organization` имеют тип 1:1*. У типов отсутствуют поля
