### ISSUE TITLE
Support to skip a multihead connection / union variants in a query

### ISSUE THREAD

**Issue by opomuc** [tarantool/graphql.0#244]
Following test query will throw an error:
```
local query = [[
    query obtainHeroes($hero_id: String) {
        hero_collection(hero_id: $hero_id) {
            hero_id
            hero_type
            banking_type
            hero_connection {
                ... on box_human_collection {
                    human_collection {
                        name
                    }
                }
            }
            hero_banking_connection {
                ... on box_array_credit_account_collection {
                    credit_account_collection {
                        account_id
                        hero_banking_id
                    }
                }
                ... on box_array_dublon_account_collection {
                    dublon_account_collection {
                        account_id
                        hero_banking_id
                    }
                }
            }
        }
    }
]]
```

```
/usr/share/tarantool/graphql/query_to_avro.lua:163: assertion failed!
stack traceback:
        [C]: in function 'assert'
        /usr/share/tarantool/graphql/query_to_avro.lua:163: in function 'union_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:81: in function 'gql_type_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:201: in function 'field_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:256: in function 'object_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:79: in function 'gql_type_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:70: in function 'gql_type_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:201: in function 'field_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:256: in function 'object_to_avro'
        /usr/share/tarantool/graphql/query_to_avro.lua:79: in function 'gql_type_to_avro'
        ...
```

**Comment by Totktonada** [comment]
The problem appears when not all branches are taken.

**Comment by Totktonada** [comment]
If it is possible to omit some variants in a query, then what result we should expect in case a retrieved object that has a type of such omitted variant?

Consider the objects tree:

```
- hero_type: starship
  hero_banking_connection:
    dublon_account_collection: !! dublon account, not credit account !!
    - account_id: dublon_account_id_1
      hero_banking_id: hero_banking_id_2
    - account_id: dublon_account_id_2
      hero_banking_id: hero_banking_id_2
    - account_id: dublon_account_id_3
      hero_banking_id: hero_banking_id_2
  hero_id: hero_id_2
  hero_connection:
    starship_collection: !! starship, not human !!
      model: Falcon-42
  banking_type: dublon
```

Suppose we omit `dublon_account_collection` and `starship_collection` variants in a query. How the result should look for, say, the following query?

```
    query obtainHumans {
        hero_collection(hero_id: "hero_id_2") {
            hero_id
            hero_type
            banking_type
            hero_connection {
                ... on box_human_collection {
                    human_collection {
                        name
                    }
                }
            }
            hero_banking_connection {
                ... on box_array_credit_account_collection {
                    credit_account_collection {
                        account_id
                        hero_banking_id
                    }
                }
            }
        }
    }
```

It can just omit non-existent variants:

```
- hero_type: starship
  hero_banking_connection: []
  hero_id: hero_id_2                                                                                                                                                           
  hero_connection: []
  banking_type: dublon
```

Or omit the entire multihead connection / union field:

```
- hero_type: starship
  hero_id: hero_id_2
  banking_type: dublon
```

I'm going to implement the former approach, because it is most straightforward.

@opomuc @Kasen Please, comment if it is important for you.
